networks:
  frontend:
  backend:

services:
  app:
    image: "docker.io/${DOCKER_USER}/asmbly-data-dashboard:${TAG}"
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - frontend
      - backend
    environment:
      TZ: "America/Chicago"
    depends_on:
      - db
      - redis
    secrets:
      - postgres-user
      - postgres-password
      - postgres-db
  db:
    image: postgres:16
    restart: unless-stopped
    networks:
      - backend
    environment:
      POSTGRES_USER_FILE: /run/secrets/postgres-user
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres-password
      POSTGRES_DB_FILE: /run/secrets/postgres-db
      TZ: "America/Chicago"
      PGTZ: "America/Chicago"
    volumes:
      - postgres:/var/lib/postgresql/data
    secrets:
      - postgres-user
      - postgres-password
  redis:
    image: redis:7.2.4
    restart: unless-stopped
    networks:
      - backend
    environment:
      TZ: "America/Chicago"

volumes:
  postgres:

secrets:
  postgres-user: 
    file: ./secrets/postgres-user.txt
  postgres-password: 
    file: ./secrets/postgres-password.txt
  postgres-db:
    file: ./secrets/postgres-db.txt