services:
  app:
    env_file:
      - .env
    restart: unless-stopped
    environment:
      TZ: "America/Chicago"
      POSTGRES_USER_FILE: /run/secrets/postgres-user
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres-password
      POSTGRES_DB_FILE: /run/secrets/postgres-db
    depends_on:
      - db
      - cache
    secrets:
      - postgres-user
      - postgres-password
      - postgres-db
  db:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_USER_FILE: /run/secrets/postgres-user
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres-password
      POSTGRES_DB_FILE: /run/secrets/postgres-db
      TZ: "America/Chicago"
      PGTZ: "America/Chicago"
    volumes:
      - postgres:/var/lib/postgresql/data
    secrets:
      - postgres-user
      - postgres-password
      - postgres-db
  cache:
    image: redis:7.2.4
    restart: unless-stopped
    environment:
      TZ: "America/Chicago"
  cron:
    env_file:
      - .env
    build: 
      context: .
      dockerfile: ./cron-service/Dockerfile
      args:
        DOCKER_BUILDKIT: 1
    depends_on:
      - db
    secrets:
      - postgres-user
      - postgres-password
      - postgres-db
    restart: unless-stopped
    environment:
      TZ: "America/Chicago"
      POSTGRES_USER_FILE: /run/secrets/postgres-user
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres-password
      POSTGRES_DB_FILE: /run/secrets/postgres-db

volumes:
  postgres:

secrets:
  postgres-user: 
    file: ./secrets/postgres-user.txt
  postgres-password: 
    file: ./secrets/postgres-password.txt
  postgres-db:
    file: ./secrets/postgres-db.txt