FROM python:3.11 as base

ENV POETRY_NO_INTERACTION=1 \
    POETRY_VIRTUALENVS_CREATE=0 \
    POETRY_HOME=/opt/poetry \
    PYTHONUNBUFFERED=1

ENV PATH="$POETRY_HOME/bin:$PATH"

RUN curl -sSL https://install.python-poetry.org | python3 -

COPY pyproject.toml poetry.lock ./

RUN poetry install --no-root

WORKDIR /app

COPY ./dash_data_dashboard ./dash_data_dashboard
COPY main.py README.md engine.py schema.py ./
COPY ./entrypoint.sh /entrypoint.sh

RUN chmod +x /entrypoint.sh

EXPOSE 8050

ENTRYPOINT ["/entrypoint.sh"]