FROM python:3.11 as base

RUN apt-get update && apt-get -y install cron

ENV POETRY_NO_INTERACTION=1 \
    POETRY_VIRTUALENVS_CREATE=0 \
    POETRY_HOME=/opt/poetry \
    PYTHONUNBUFFERED=1

ENV PATH="$POETRY_HOME/bin:$PATH"

RUN curl -sSL https://install.python-poetry.org | python3 -

COPY pyproject.toml poetry.lock ./

RUN poetry install --no-root

WORKDIR /app

COPY ./cron_service ./
COPY engine.py schema.py ./

COPY ./cron_service/crontab /etc/cron.d/crontab

RUN chmod 0644 /etc/cron.d/crontab

RUN /usr/bin/crontab /etc/cron.d/crontab

ENTRYPOINT ["cron", "-f", "-l", "8"]